// Mocks generated by Mockito 5.4.6 from annotations
// in futbol_ai/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:futbol_ai/data/datasources/gemini_datasource.dart' as _i8;
import 'package:futbol_ai/data/models/analysis_model.dart' as _i2;
import 'package:futbol_ai/data/models/chat_message_model.dart' as _i6;
import 'package:futbol_ai/data/repositories/analysis_repository.dart' as _i3;
import 'package:futbol_ai/data/repositories/chat_repository.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAnalysisModel_0 extends _i1.SmartFake implements _i2.AnalysisModel {
  _FakeAnalysisModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AnalysisRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalysisRepository extends _i1.Mock
    implements _i3.AnalysisRepository {
  MockAnalysisRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AnalysisModel> getOrRequestAnalysis({
    required String? matchId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOrRequestAnalysis, [], {
              #matchId: matchId,
              #userId: userId,
            }),
            returnValue: _i4.Future<_i2.AnalysisModel>.value(
              _FakeAnalysisModel_0(
                this,
                Invocation.method(#getOrRequestAnalysis, [], {
                  #matchId: matchId,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.AnalysisModel>);

  @override
  _i4.Future<_i2.AnalysisModel?> getCachedAnalysis({
    required String? matchId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedAnalysis, [], {
              #matchId: matchId,
              #userId: userId,
            }),
            returnValue: _i4.Future<_i2.AnalysisModel?>.value(),
          )
          as _i4.Future<_i2.AnalysisModel?>);

  @override
  _i4.Stream<String> streamAnalysisStatus({
    required String? matchId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#streamAnalysisStatus, [], {
              #matchId: matchId,
              #userId: userId,
            }),
            returnValue: _i4.Stream<String>.empty(),
          )
          as _i4.Stream<String>);
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i5.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i6.ChatMessageModel>> streamMessages(String? matchId) =>
      (super.noSuchMethod(
            Invocation.method(#streamMessages, [matchId]),
            returnValue: _i4.Stream<List<_i6.ChatMessageModel>>.empty(),
          )
          as _i4.Stream<List<_i6.ChatMessageModel>>);

  @override
  _i4.Future<String> sendMessage({
    required String? matchId,
    required String? message,
    List<_i6.ChatMessageModel>? history,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [], {
              #matchId: matchId,
              #message: message,
              #history: history,
            }),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#sendMessage, [], {
                  #matchId: matchId,
                  #message: message,
                  #history: history,
                }),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<int> getTodayMessageCount(String? matchId) =>
      (super.noSuchMethod(
            Invocation.method(#getTodayMessageCount, [matchId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> clearChat(String? matchId) =>
      (super.noSuchMethod(
            Invocation.method(#clearChat, [matchId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [CloudFunctionDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCloudFunctionDatasource extends _i1.Mock
    implements _i8.CloudFunctionDatasource {
  MockCloudFunctionDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<Map<String, dynamic>> requestAnalysis(String? matchId) =>
      (super.noSuchMethod(
            Invocation.method(#requestAnalysis, [matchId]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<String> sendChatMessage({
    required String? matchId,
    required String? message,
    List<Map<String, String>>? history,
    Map<String, dynamic>? matchData,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendChatMessage, [], {
              #matchId: matchId,
              #message: message,
              #history: history,
              #matchData: matchData,
            }),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#sendChatMessage, [], {
                  #matchId: matchId,
                  #message: message,
                  #history: history,
                  #matchData: matchData,
                }),
              ),
            ),
          )
          as _i4.Future<String>);
}
