include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.mocks.dart'
  errors:
    missing_return: error
    dead_code: warning
    unused_import: warning
    unused_local_variable: warning
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - avoid_print
    - avoid_unnecessary_containers
    - prefer_single_quotes
    - use_key_in_widget_constructors
    - sized_box_for_whitespace
    - prefer_is_empty
    - prefer_is_not_empty
    - unnecessary_string_interpolations
    - unnecessary_this
    - prefer_const_literals_to_create_immutables
    - prefer_relative_imports
